// Using decorators from tsoa generate the spec

import { generateSpec, ExtendedSpecConfig } from 'tsoa';
import { ApiGatewayV2 } from 'aws-sdk';
const apiGatewayV2 = new ApiGatewayV2({
  region: 'us-east-1',
});

export const downloadApiGatewaySpec = async (
  ApiId: string
): Promise<Record<string, unknown>> => {
  const apiSpec = await apiGatewayV2
    .exportApi({
      ApiId,
      OutputType: 'JSON',
      Specification: 'OAS30',
    })
    .promise();

  const apiString = apiSpec.body?.toString();
  return apiString && JSON.parse(apiString);
};

const deepMergeApiSpec = (apiGatewaySpec: Record<string, unknown>) => {
  const specOptions: ExtendedSpecConfig = {
    entryFile: './src/app.ts',
    description: `API Docs generated by merging APIGateway, and tsoa generated swagger`,
    specVersion: 3,
    outputDirectory: 'docs',
    controllerPathGlobs: ['src/controllers/*.ts'],
    noImplicitAdditionalProperties: 'throw-on-extras',
    spec: apiGatewaySpec,
    specMerging: 'deepmerge',
  };

  return generateSpec(specOptions);
};

(async () => {
  const outputs: Record<
    string,
    Record<string, string>
  > = require('./api-id.json');

  const { apiId } = Object.values(outputs)[0];

  const apiGatewaySpec = await downloadApiGatewaySpec(apiId);
  return deepMergeApiSpec(apiGatewaySpec);
})();
